<ValidatedInputWidget>:
    orientation: 'vertical'
    padding: 20
    spacing: 20

    canvas.before:
        Color:
            rgba: 1, 1, 1, 1  # fundo branco
        Rectangle:
            pos: self.pos
            size: self.size

    TextInput:
        hint_text: 'Digite ao menos 5 letras, sem números'
        multiline: False
        font_size: 20
        on_text: root.validated_text = self.text

    Label:
        text: root.validated_text
        font_size: 22
        color: 0, 0, 0, 1
